// Dev tools
user_pref("devtools.chrome.enabled", true);
user_pref("devtools.debugger.remote-enabled", true);
user_pref("devtools.debugger.prompt-connection", true);

user_pref("browser.tabs.hoverPreview.showThumbnailDelay", 1000);
user_pref("findbar.highlightAll", true);
user_pref("full-screen-api.transition-duration.enter", "0 0");
user_pref("full-screen-api.transition-duration.leave", "0 0");
user_pref("full-screen-api.warning.timeout", 0);
user_pref("general.smoothScroll", true);
user_pref("general.smoothScroll.currentVelocityWeighting", "0.15");
user_pref("general.smoothScroll.mouseWheel.durationMaxMS", 250);
user_pref("general.smoothScroll.mouseWheel.durationMinMS", 250);
user_pref("general.smoothScroll.msdPhysics.enabled", true);
user_pref("general.smoothScroll.msdPhysics.motionBeginSpringConstant", 400);
user_pref("general.smoothScroll.msdPhysics.regularSpringConstant", 600);
user_pref("general.smoothScroll.msdPhysics.slowdownMinDeltaMS", 120);
user_pref("general.smoothScroll.other.durationMaxMS", 500);
user_pref("general.smoothScroll.pages.durationMaxMS", 350);
user_pref("general.smoothScroll.stopDecelerationWeighting", "0.8");
user_pref("mousewheel.min_line_scroll_amount", 22);
user_pref("gfx.webrender.all", true);
user_pref("gfx.webrender.enabled", true);
user_pref("layers.acceleration.force-enabled", true);
user_pref("layout.css.color-mix.enabled", true);
user_pref("layout.css.container-queries.enabled", true);
user_pref("layout.css.has-selector.enabled", true);
user_pref("svg.context-properties.content.enabled", true);
user_pref("toolkit.legacyUserProfileCustomizations.stylesheets", true);
user_pref("ui.textHighlightBackground", "#FFD500");
user_pref("ui.textHighlightForeground", "#000000");
user_pref("ui.textSelectAttentionBackground", "#FF9632");
user_pref("ui.textSelectAttentionForeground", "#000000");
user_pref("ui.textSelectBackground", "#CCE2FF");
user_pref("ui.textSelectForeground", "#000000");
